### ISSUE TITLE
Specify electrode type for ElectrodeGrid

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#122]
`ElectrodeGrid` currently assumes all electrodes are `DiskElectrode` objects.

To be more flexible, constructor needs to accept an electrode type. Thing is, `DiskElectrode` needs a radius, but `PointSource` does not. Therefore, we also need a way to specify optional keyword arguments that can be passed to the electrode constructor.

**Comment by arokem** [comment]
Add a ‘**elec_kwargs’ input to the grid constructor?

**Comment by mbeyeler** [comment]
Closed via #150
