### ISSUE TITLE
[DOC] Error when installing p2p: numpy.ufunc size changed

### ISSUE THREAD

**Issue by ZhuoweiCheng** [pulse2percept/pulse2percept#142]
When I tried to import pulse2percept as p2p, it returned the following error: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by mbeyeler** [comment]
Any chance you are using NumPy 1.15? It seems to be an issue with NumPy itself, so upgrading to 1.16 should fix it:

    pip install numpy==1.16

Source: https://twitter.com/andrewplested/status/1141991949571940352?lang=en

**Comment by mbeyeler** [comment]
We should add an entry to the [Troubleshooting Guide](https://pulse2percept.readthedocs.io/en/latest/install.html#troubleshooting) section of the [Installation Instructions](https://github.com/pulse2percept/pulse2percept/blob/master/doc/install.rst)
