### ISSUE TITLE
Time should be in milliseconds

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#170]
Time is currently in SI units (seconds), but space (microns) and currents (uA) are not. Sure, we could go all SI. But it's more convenient to use the dimension that is most relevant to the application. Dealing with `1e-6` floats is just painful...

Thus time should be in milliseconds (especially in `TimeSeries` etc.)

**Comment by arokem** [comment]
In nitime, we chose to represent time in a base unit of pico-seconds, represented in int64. That way, for any reasonable time calculations you would never have to deal with floating point values. OTOH, you have to deal with some pretty large integers, and if you want to represent large durations, you can end up overflowing.

**Comment by mbeyeler** [comment]
An alternative would be to use a package that can handle physical units (if we can avoid a large dependency such as as sympy or astropy). This one seems light-weight and fast (Cython): https://github.com/cjrh/misu

**Comment by mbeyeler** [comment]
Closed via #178
