### ISSUE TITLE
Add thresholding for axon_contrib (for VR shader optimization)

### ISSUE THREAD

**Issue by NeuroscienceScripts** [pulse2percept/pulse2percept#211]
https://github.com/pulse2percept/pulse2percept/blob/c8031c930218261defab751419c3c9d7394671da/pulse2percept/models/beyeler2019.py#L296

change to: 
if(sensitivity  > threshold)
          ...

**Comment by mbeyeler** [comment]
This can be done as part of #208

**Comment by mbeyeler** [comment]
Closed via #215
