### ISSUE TITLE
[BUG] change an instruction of the contributing guidelines

### ISSUE THREAD

**Issue by aiwenxu** [pulse2percept/pulse2percept#245]
https://pulse2percept.readthedocs.io/en/latest/developers/contributing.html#contributing-code
https://github.com/pulse2percept/pulse2percept/blob/master/CONTRIBUTING.rst

In 5.1, change "compare across forks" to "compare & pull request" since GitHub has updated its interface.

**Comment by mbeyeler** [comment]
Closed via #257
