### ISSUE TITLE
[DOC] Add an example on how to load the Nanduri dataset

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#254]
Add an example to the gallery that showcases how to load the Nanduri dataset. Also add a line in [datasets.rst](https://github.com/pulse2percept/pulse2percept/blob/master/doc/topics/datasets.rst) under "Dataset loaders" to mention `load_nanduri2012`.

**Comment by WadeVaresio** [comment]
[Branch](https://github.com/WadeVaresio/pulse2percept/tree/nanduri2012-dataset-example) works to address this issue.
