### ISSUE TITLE
[DOC] Use pandas plotter in Beyeler dataset example

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#271]
We can use the built-in pandas plotter for the histogram (last figure) of the `plot_data_beyeler2019.py` example:

Starting at [line 159 ](https://github.com/pulse2percept/pulse2percept/blob/master/examples/datasets/plot_data_beyeler2019.py#L159), replace:

```
plt.hist(data.eccentricity)
plt.xlabel('phosphene elongation')
plt.ylabel('count')
```

with:
```
data.eccentricity.plot(kind='hist')
plt.xlabel('phosphene elongation')
```

**Comment by aiwenxu** [comment]
working on this issue
