### ISSUE TITLE
[ENH] rgb2gray when image is grayscale

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#279]
`The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.`

Change line [105](https://github.com/pulse2percept/pulse2percept/blob/master/pulse2percept/stimuli/images.py#L105) in `pulse2percept/stimuli/images.py` from:

```
img = rgb2gray(img)
```

to

```
if img.ndim == 3:
    img = rgb2gray(img)
```

**Comment by omizrahi99** [comment]
Can I take this?
