### ISSUE TITLE
[BUG] Setting axlambda=0 in AxonMapModel

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#303]
To turn axonal streaks off, `AxonMapModel` should be run with `axlambda=0`. Theoretically, this should then be the same as `ScoreboardModel`. In reality, it looks different - probably because there is a division by zero error somewhere. Investigate!

**Comment by Conrad-Crowley** [comment]
There is a division by zero by a variable declaration within the `beyeler2019.py` file. 
The class `AxonMapSpatial ` contains a method `calc_axon_contribution(self, axons)` which declares a variable:
`sensitivity = np.exp(-d2[idx_d2] / (2.0 * self.axlambda ** 2))` which is division by zero for `axlambda=0`.
