### ISSUE TITLE
[BUG] Size of implant's electrode don't seem to agree with the provided electrode radius

### ISSUE THREAD

**Issue by alex-bene** [pulse2percept/pulse2percept#340]
**Bug Description**
Trying to visualize various custom parametrized square implants, it seems like the 'r' parameter does not agree with the radius of the electrode when the implant is visualized using plot_implant_on_axon_map.

**To Reproduce**
`
plot_implant_on_axon_map(ProsthesisSystem(ElectrodeGrid((2, 2), r=1000, spacing=(2000), etype=DiskElectrode)))
`

**Expected behavior**
In the diagram from the above snippet, there should be 4 electrodes with a radius of 1000 microns touching each other and covering a total area of 4000x4000 microns.

**Screenshots**
However we get this
![image](https://user-images.githubusercontent.com/34627055/105116138-d3530f00-5ad2-11eb-8086-d0b0d41939a6.png)

**Why this is happening**
Looking around the code this seems to trackback to this line of code where the markersize is set
https://github.com/pulse2percept/pulse2percept/blob/9acf65990c51ec4612eef5e0c32b8fb218beb13b/pulse2percept/viz/axon_map.py#L161

**In the End**
In the end, what matter is if it is just a visual thing and you couldn't find how to better visualize it (because I looked into it and I didn't find something very useful except that the units of markersize are points^2 --> area) or if the 'r' in the code snippet above means something different than the radius of the electrode in microns (since this would have impact on the results from the simulations)

**Comment by mbeyeler** [comment]
Thank you for this detailed report. Yeah, as you pointed out towards the end, it is a pain to get the marker to show up with the correct size because of the auto-scaling... I realize though that it is important to get this right - I will look into it

**Comment by alex-bene** [comment]
In my case, it just happened to be using the visualization to check for electrode overlaps so it was a bit jarring. In any case, I suppose if it was documented that the visual size of the electrode is not the real one would be a good start.

As for a possible solution, I suppose one could use the circle object from matplotlib.
```
ax.add_patch(plt.Circle((implant[e].x, implant[e].y), implant[e].r, color='w'))
```
As for using the 'markersize' option, according to kite is seems like:
> Using matplotlib.pyplot.plot() determines the width of points. Using matplotlib.pyplot.scatter() determines the area of points
[source](https://www.kite.com/python/answers/how-to-set-point-size-in-a-matplotlib-plot-in-python)

In any case, it seems like:
`actual_area        = markersize*k ` in the case of scatter
`actual_diameter = markersize*k ` in the case of plot
where k could be calculated through some measurements or trial and error maybe. (although I strongly believe that the use of plt.Circle is the best)

I will try to make some of the above modifications probably in the next week if I find some time.

**Comment by mbeyeler** [comment]
A PR would be greatly appreciated! Then we can ship this as part of v0.7, which is imminent (~next couple weeks)

**Comment by mbeyeler** [comment]
Looking further into this: The use of these plotters should actually be deprecated. This is a documentation fail.

The new preferred way is to use the `plot` methods of the corresponding object - those correctly use  `Circle`.

For example, plot Argus II:
```
import pulse2percept as p2p
p2p.implants.ArgusII().plot()
```

![image](https://user-images.githubusercontent.com/5214334/107820577-ddfa7000-6d2f-11eb-9a69-cc717cc2b5dc.png)


Plot Argus II on axon map:
```
p2p.models.AxonMapModel().plot()
p2p.implants.ArgusII().plot()
```

![image](https://user-images.githubusercontent.com/5214334/107820609-efdc1300-6d2f-11eb-829a-688487f1011c.png)

Or use your own implant:
```
p2p.implants.ElectrodeGrid((2, 2), r=1000, spacing=2000, etype=p2p.implants.DiskElectrode).plot()
```

![image](https://user-images.githubusercontent.com/5214334/107820767-2c0f7380-6d30-11eb-9928-bec427ca536a.png)

**Comment by alex-bene** [comment]
Ohh, I actually didn't test that. It seems you're right. Well as a "plus" I suppose the same functionality could be added to the "plot_implant_on_axon_map" function for consistency or completely remove it.
