### ISSUE TITLE
Build Stimulus from list of time points?

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#343]
It seems like this should be possible:

```
electrodes = ['A1', 'B2', 'C3']
implant.stim = [{e: 1} for e in electrodes]
```

The expectation would be that the implant would expand this to a 2D array (electrodes x time points) where only one electrode would be active at any given time point, equivalent to this:

```
implant.stim = Stimulus(np.eye(3), electrodes=['A1', 'B2', 'C3'])
```

It's easy to do with `np.eye` if you know how, but it's not intuitive for users who cannot see behind the curtains of how `Stimulus` is built. We could provide a `rasterize` or `multiplex` function that does this for you. Or tweak the `Stimulus` factory so that the first code snippet works.

**Comment by jgranley** [comment]
Is it not enough that they can do:
```
electrodes = ['A1', 'B2', 'C3']
implant.stim = {e: 1 for e in electrodes}
```
If not, I have a quick fix I can implement, as I was already making changes to the stimulus factory for metadata updates

**Comment by mbeyeler** [comment]
That's different - yours is saying activate A1, B2, C3 at the same time with amplitude 1. The above is saying, in the first frame activate only A1 with amplitude 1 (B2 and C3 are 0), in the second frame only B2, ...

You could also achieve the first one with:
```
implant.stim = {'A1': [1, 0, 0], 'B2': [0, 1, 0], 'C3': [0, 0, 1]}
```
(one-hot encoding) but this would be cumbersome if you have many electrodes to activate.

After thinking more about this, I'm not sure what I suggested above is the best way to go.
I guess that one is not allowed because passing a list is interpreted not as a list of time points, but as a list of electrodes (e.g., the first element contains the stimulus for electrode 0, and the list must have the same number of elements as electrodes in the implant).

So the problem is bigger than that: what's the best way to specify sparse activation of electrodes across different time points?

**Comment by mbeyeler** [comment]
Use `stim.append()` if you have to patch different stimuli together. wontfix
