### ISSUE TITLE
[BUG] Axon Map plot() not centered on fovea for left eye

### ISSUE THREAD

**Issue by jgranley** [pulse2percept/pulse2percept#364]
When plotting the axon map model in the left eye, the plot is not centered correctly over the fovea, and the coordinates do not line up (fovea is not at (0,0))

```
model = AxonMapModel(eye="LE")
model.plot()
```

Screenshot:

![image](https://user-images.githubusercontent.com/25232557/114833422-6a52fe80-9d84-11eb-864c-7f5eec66284b.png)

**Comment by mbeyeler** [comment]
Oof. On top of that, the nasal <=> temporal label is wrong

**Comment by jgranley** [comment]
I could be wrong, but I thought that the label was correct. How I was interpreting this was that the fovea should be to the right of the optic disc (at something like 7000, 0 on this plot), and everything else was correct, but the plot just isn't showing the correct region. 

If the label is wrong here, then I think it is also wrong on the plot for the right eye (they're currently the reverses of each other)

**Comment by mbeyeler** [comment]
Ah, I see. The fovea should lie at (0, 0) though, so then maybe the axis labels are wrong, too. I don't know, but will look into it
