### ISSUE TITLE
Generating a stimulus from an image - PRIMA40

### ISSUE THREAD

**Issue by mai-amber** [pulse2percept/pulse2percept#481]
Hi! I would really appreciate your help... first of all, I love this so thank you! I succeeded in creating a stimulus from an image for ARGUSII, now I would like to do the same for PRIMA40, but am getting this error ValueError: the input array must have size 3 along `channel_axis`, got (25, 28). I am not sure what to do... thank you so much in advance.

**Comment by mbeyeler** [comment]
Hi! Which version of p2p are you using (`import pulse2percept as p2p; print(p2p.__version__)`)? Because with the latest version, you should be able to just do this (e.g., in Google Colab):

```
!pip install git+https://github.com/pulse2percept/pulse2percept
import pulse2percept as p2p
p2p.implants.PRIMA40(stim=p2p.stimuli.LogoBVL())
```

If that doesn't work, it would help to see a code snippet that led to the above error.

Thanks,
Michael

**Comment by mai-amber** [comment]
Hi! Thank you so much for the quick response! 
I am running v0.7.1. When I ran the code you suggested:
`!pip install git+https://github.com/pulse2percept/pulse2percept
import pulse2percept as p2p
p2p.implants.PRIMA40(stim=p2p.stimuli.LogoBVL())`
I got the following error:
ValueError: Electrode "532" not found in implant.

**Comment by mbeyeler** [comment]
It looks like the upgrade to the latest p2p version didn't go through. If you run this in a Colab notebook, it will work. I guess you're running on your local machine, so if you open a terminal/command line window and type:

```
$ pip uninstall -y pulse2percept
$ pip install git+https://github.com/pulse2percept/pulse2percept
```

and try again, you should be good to go. If it still doesn't work, I'll need to know a little more (are you on Win/Mac/Linux, how did you install) to help you. Fingers crossed!

**Comment by mai-amber** [comment]
Yes I am running Jupyter Lab locally on a Mac. 
This seems to have helped as I am no longer getting an error, however this is the output:
`PRIMA40(earray=ElectrodeGrid, eye='RE', preprocess=False, 
        safe_mode=False, stim=Stimulus)`
But no image... (thank you so much for your patience)

**Comment by mbeyeler** [comment]
Great! So now you have a working stimulus & implant, but you still need a model, then you can call predict & see the output, e.g.:

```
prima = p2p.implants.PRIMA40(stim=p2p.stimuli.LogoBVL())
model = p2p.models.ScoreboardModel(rho=40)
model.build()
percept = model.predict_percept(prima)
percept.plot()
```

see https://pulse2percept.readthedocs.io/en/latest/examples/stimuli/plot_image_stim.html#using-the-image-as-input-to-a-retinal-implant

But I am closing this issue as the problem seems to be resolved. Thanks

**Comment by mai-amber** [comment]
It worked perfectly, thank you so much for your help!
