### ISSUE TITLE
Simulating videos - Charge accumulation in Nanduri / Horsager

### ISSUE THREAD

**Issue by kfeeeeee** [pulse2percept/pulse2percept#85]
Hi guys, 
First of all thank you very much for your framework :+1: 
When simulating longer videos I have noticed that the percepts become black after time. After further investigation I think it is because of the charge accumulation making the system less sensitive the more charge is accumulated. However, sensitivity is never restored as far as I can see (and was of no interest in generating the model I guess).

So there are two questions that I have right now:
1.) Are my assumptions correct?
2.) Do you know of any "plausible" way, e.g. a known model etc. for "resetting" the sensitivity?

Thanks in advance

EDIT: To be more precise: I am simulating a 20 second clip (25fps) of a still image for testing (amplitude encoded between [0,1] and an implant with a working frequency between 1-20 Hz (1ms cathodic pulses)). 

Attached you can see two responses (working frequency 5Hz and 20Hz) of a fixed position within the percept. It is clear to me that the sensitivity drops faster for pulses with 20Hz, since the accumulated charge will increase faster than with 5Hz, however, in both cases the accumulated charge will linearly increase over time making the system insensitive in the long run.  
![wf5](https://user-images.githubusercontent.com/6988333/44846237-2a30c300-ac50-11e8-874a-d699625d5332.png)
![wf20](https://user-images.githubusercontent.com/6988333/44846244-2bfa8680-ac50-11e8-93d2-406ae0a8da86.png)

**Comment by ionefine** [comment]
Hi, has someone responded to this? The main code-writer just had a baby so I’m worried if fell through the cracks.

If this hasn’t been dealt with I’ll answer properly …

Ione

**Comment by arokem** [comment]
@ionefine : feel free to jump in!

**Comment by kfeeeeee** [comment]
Congratulations :-) . I think this might be a bit more of a model issue rather than a programming issue.
