### ISSUE TITLE
pip install on Windows produces error in fast_retina.pyx

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#88]
A user reports that pip install fails with error "'pulse2percept/fast_retina.pyx' doesn't match any files". It's time for a new release

**Comment by burachuk** [comment]
`pip install pulse2percept` works great in [colab.research.google.com](colab.research.google.com) to play with .ipynb

**Comment by mbeyeler** [comment]
This is super cool!

**Comment by mbeyeler** [comment]
Perhaps this is a platform-specific issue. I'll try to find out more

**Comment by Whitey2071** [comment]
Hi! Love the work you've done and would like to make use of it in my PhD work but I am experiencing the issue that's been mentioned here. I am on Windows 10 running Python 3.6.8 and have all the dependencies downloaded. Let me know if I can provide further information to help resolve the issue.

**Comment by mbeyeler** [comment]
Looking forward to learning more about your research! What worked for others is to install the development version for now, using `git clone` and `python setup.py install`: https://github.com/uwescience/pulse2percept#development-version

**Comment by Whitey2071** [comment]
Thank you very much for your quick response! The installation was successful on an Ubuntu 16 environment I'm running but I will implement the work-around you've suggested here on Windows 10.

**Comment by mbeyeler** [comment]
Closed via #130
